name: Quarto Publish

on:
  push:
    branches:
      - main  # Se il tuo branch si chiama 'master', scrivi 'master' al posto di 'main'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Installa Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Converti e Pubblica su GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
